server:
  port: 8105
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
spring:
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/rent_car
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect